# Generated by Django 5.0.4 on 2024-05-06 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.EmailField(blank=True, max_length=255, null=True, verbose_name='department')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('country', models.CharField(max_length=85, verbose_name='Country')),
                ('city', models.CharField(max_length=85, verbose_name='City')),
                ('street', models.CharField(blank=True, max_length=135, null=True, verbose_name='St.')),
                ('building', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='"Bld.')),
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Network Node')),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Debt')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('level', models.IntegerField(choices=[(0, 'Factory'), (1, 'Retailer'), (2, 'Consumer')], default=1)),
                ('contacts', models.ManyToManyField(related_name='organisation', to='networks.contacts', verbose_name='Contacts')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_by', to='networks.networknode', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Network Node',
                'verbose_name_plural': 'Network Nodes',
            },
        ),
        migrations.AddField(
            model_name='contacts',
            name='network_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='networks.networknode'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('sales_channel', models.ManyToManyField(blank=True, related_name='product', to='networks.networknode')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='networknode',
            name='products',
            field=models.ManyToManyField(related_name='seller', to='networks.product', verbose_name='Products'),
        ),
    ]
