# Generated by Django 5.0.4 on 2024-05-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='department'),
        ),
    ]
